name: Node CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: yikesable/workflows/.github/workflows/test.yml@main
    with:
      node-versions: '18,20,21'
      os: 'ubuntu-latest'
