name: Type Checks, Published Types

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '14 5 * * 1'

permissions:
  contents: read

jobs:
  type-check:
    uses: yikesable/workflows/.github/workflows/type-check.yml@main
    with:
      ts-prebuild-script: 'build'
      # ts-versions: ${{ github.event.schedule && 'next' || '5.5,next' }}
      ts-versions: 'next'
      ts-libs: 'es2020;esnext'
      ts-working-directory: 'test-published-types'
